server:
  port: 8787

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/containers
    username: postgres
    password: postgres123

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog.yaml
    driver-class-name: org.postgresql.Driver